name: Node.js CI 

on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code 
        uses: actions/checkout@v3
      - name: install npm react-scripts
        run: npm install react-scripts --save-dev
      - name: install dependencies
        run: npm install -g npm@6
      - name: npm start 
        run: npm start 
      - name: Linter (ESlint)
        run: npm run lint 
      - name: Formatter (prettier)
        run: npm run prettier
      - name: test (jest)
        env:
         CI: true
        run: npm run test
      - name: build 
        run: npm run build 
#!
